### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by MarcoWorms** [hashlab/hash-landingpage#3]
- [x] remove unused gizmo font
- [x] better icons quality
- [x] make buttons work + current page cue
- [x] animations
- [x] fix HASH little square
- [x] add favicon
- [x] auto snap
- [x] vanish texts on scroll up
- [x] analytics
